apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: demo-main
spec:
  type: LoadBalancer
  selector:
    app: demo-app
  ports:
    - name: https
      port: 8081        # service port
      targetPort: 8081  # container port
